#!/bin/sh

case "$1" in
    start)
	/sbin/acpid -a /etc/acpid.conf -M /etc/acpid.map
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
