#!/bin/sh

case "$1" in
    start)
        modprobe octonet
        lua /var/monitor/fancontrol.lua
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
